### ISSUE TITLE
How to display KWM spaces and status in the system menubar

### ISSUE THREAD

**Issue by neon64** [matthewdias/dotfiles#1]
I stumbled across your dotfiles from the [kwm wiki](https://github.com/koekeishiya/kwm/wiki/Sample-Configurations).

I was wondering how you achieved the spaces icons/numbers and `[bsp]` label in the top-right corner of this screenshot:

https://raw.githubusercontent.com/matthewdias/dotfiles/master/screen.png

I found the `bar` script which I think generates the content, but how do you display that in the GUI?
https://github.com/matthewdias/dotfiles/blob/master/.kwm/scripts/bar

Thanks very much if you could help. I realise this isn't an 'issue' per se but I don't know how else to make contact.

**Comment by matthewdias** [comment]
Check out these options
- [TextBar](http://www.richsomerfield.com/apps/)
- [bitbar](https://getbitbar.com/)
- [koe's ubersicht](https://github.com/koekeishiya/nerdbar.widget)

**Comment by neon64** [comment]
Ok thanks very much for your help. I already tried that Übersicht widget but I found that I needed to access system menus too often for it to be useful. I will download TextBar and bitbar and try them out.
